---
- hosts: localhost
  become: yes
  tasks:

    - include_tasks: pip.yml

    - name: build image from cloned repo
      docker_image:
        name: jenkins
        build:
          pull: true
          path: /home/ubuntu/jenkins-docker/
        source: build
